#!/bin/bash

echo what is your project name?

read project

#create the directory and put stuff inside it.
mkdir $project
cd $project
touch index.html
mkdir css js img
touch js/script.js css/style.css


